name: Security Scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check for forbidden files
      run: |
        echo "Checking for forbidden files..."
        if git rev-parse --verify origin/main >/dev/null 2>&1; then
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || echo "")
        fi
        if echo "$CHANGED_FILES" | grep -E '\.env$|\.sqlite|\.log|\.db$'; then
          echo "❌ Forbidden files detected!"
          echo "Please remove .env, .sqlite, .log, or .db files from your commit."
          exit 1
        else
          echo "✅ No forbidden files detected"
        fi

    - name: Run pip-audit
      run: pip-audit

    - name: Run bandit
      run: bandit -r core/ -ll
