name: Smoke Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: brokercursor_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PostgreSQL (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install postgresql --params '/Password:postgres' -y
        net start postgresql-x64-15

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure environment
      run: |
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_NAME=brokercursor_test" >> .env
        echo "DB_USER=postgres" >> .env
        echo "DB_PASSWORD=postgres" >> .env
        echo "INBOX_PATH=modules/broker-reports/inbox" >> .env
        echo "ARCHIVE_PATH=modules/broker-reports/archive" >> .env
        echo "PARSED_PATH=modules/broker-reports/parsed" >> .env
        echo "MAX_FILE_SIZE_MB=50" >> .env
        echo "SUPPORTED_EXTENSIONS=.html,.txt,.pdf,.md" >> .env

    - name: Initialize database
      run: python core/scripts/init_db.py

    - name: Run smoke test
      run: python core/scripts/verify/smoke_test.py

    - name: Upload smoke test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-report-${{ matrix.os }}
        path: diagnostics/smoke_test_report.md
        retention-days: 30

    - name: Upload diagnostics
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: diagnostics-${{ matrix.os }}
        path: diagnostics/
        retention-days: 30
